spring.application.name=aiassistant

app.ai.provider=${APP_AI_PROVIDER:fake}

spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=gpt-4.1-mini

#spring.ai.openai.chat.options.model=gpt-4.1-nano


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/aiassistant}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:aiassistant}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aiassistant}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

