spring.application.name=aiassistant
#app.ai.provider=fake
app.ai.provider=openai
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.chat.options.model=gpt-4.1-nano


spring.datasource.url=jdbc:postgresql://localhost:5432/aiassistant
spring.datasource.username=aiassistant
spring.datasource.password=aiassistant

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true