spring.application.name=aiassistant
#app.ai.provider=fake
app.ai.provider=openai
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.chat.options.model=gpt-4.1-mini
spring.ai.openai.chat.options.model=gpt-4.1-nano
